language: python
os: linux
dist: xenial
python:
  - 3.8
  - 3.9
install:
   - "pip install -r requirements.txt"
   - "pip install -r test_requirements.txt"
   - "./setup.py develop"
   - "pip install coveralls"
   - "pip install pytest"
   - "pip install mypy"
script:
   - export PYTHONPATH=./src:$PYTHONPATH
   - make test_coverage
   - make typecheck
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq python-dev libyaml-dev libxml2-dev libxslt-dev libsofthsm softhsm opensc libengine-pkcs11-openssl
after_success:
   coveralls
