# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04", "ubuntu-22.04"]
        python: ["3.9", "3.10", "3.11", "3.12"] #Disable 3.13 until https://github.com/TheKevJames/coveralls-python/issues/549 is fixed
    runs-on:  ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "setuptools<70.0.0" wheel
        pip install -e ".[dev]"

    - name: Run tests
      run: |
        # Using 'python -m' is the most reliable way to invoke these 
        # when the PATH is acting up in CI
        python -m coverage erase
        python -m pytest --cov=src/pyff
